---
linters:
  disable-all: false
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - nolintlint
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"

linters-settings:
  funlen:
    lines: 100

  lll:
    line-length: 140

  dupl:
    threshold: 450

run:
  concurrency: 10
  timeout: 10m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - scripts/
    - vendor/
    - docs/

  skip-files:
    - Makefile
    - README.md
    - Dockerfile

severity:
  default-severity: error

service:
  golangci-lint-version: 1.27.x
  prepare:
    - make local.check
